version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - CLIENT_URL=${CLIENT_URL}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

    labels:
      - homepage.group=Infrastructure & Admin
      - homepage.name=Budget App
      - homepage.icon=mdi-cash-multiple
      - homepage.href=http://server:3000
